#!/bin/bash
#for dpi in 120 160 240 320
for dpi in 120 160 240 320 480 640
do
  rm -rf ${dpi}dpi
  mkdir ${dpi}dpi 
  for file in *.svg 
  do
    echo
    echo "$dpi dpi: $file" 
    if [ "$file" == "tileImageNotCached.svg" ] || [ "$file" == "tileImageNotDownloaded.svg" ]; then
      f=90
    else
      f=`echo $dpi*90/240 | bc`
    fi
    inkscape --export-png=${dpi}dpi/`echo $file | sed s/\.svg$/.png/` --export-dpi=$f $file 2>/dev/null
  done 
done

