#!/bin/bash 
function remote {
  gcloud compute ssh ubuntu-desktop -- $*
}
#remote sudo apt --assume-yes install git openjdk-8-jre
#remote 'mkdir -p Apps && mkdir -p Apps/android && cd Apps/android && wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.26/android-studio-2020.3.1.26-linux.tar.gz'
#remote 'cd Apps/android && tar zxf android-studio-2020.3.1.26-linux.tar.gz'
#remote mkdir -p Apps/android/android-sdk
#remote 'cd Apps/android && wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip'
#remote 'cd Apps/android/android-sdk && unzip ../commandlinetools-linux-7583922_latest.zip && mv cmdline-tools/* . && rmdir cmdline-tools'
#remote 'cd Apps/android && wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip'
#remote 'cd Apps/android && unzip android-ndk-r16b-linux-x86_64.zip'
#remote 'cd Apps && git clone https://github.com/grueni75/GeoDiscoverer'
#remote 'bash -c '\''echo "source ~/Apps/GeoDiscoverer/GCloud/.androidrc" >>~/.bashrc'\'''
echo "You can start Android Studio by executing ~/Apps/android-studio/bin/studio.sh"

